
# Add 'area/project' label to changes in basic project documentation and .github folder, excluding .github/workflows
area/project:
- changed-files:
  - any-glob-to-any-files: 
    - .github/**
    - LICENSE
    - AUTHORS
    - MAINTAINERS
    - PROJECT.md
    - README.md
    - .gitignore
    - codecov.yml
  - all-globs-to-all-files: '!.github/workflows/*'

# Add 'area/github-actions' label to changes in the .github/workflows folder
area/github-actions:
  - changed-files:
    - any-glob-to-any-files: '.github/workflows/**'

# Add 'area/bake' label to changes in the bake
area/bake:
  - changed-files:
    - any-glob-to-any-files: 'bake/**'

# Add 'area/bake/compose' label to changes in the bake+compose
area/bake/compose:
  - changed-files:
    - any-glob-to-any-files:
      - bake/compose.go
      - bake/compose_test.go

# Add 'area/build' label to changes in build files
area/build:
  - changed-files:
    - any-glob-to-any-files: 'build/**'

# Add 'area/builder' label to changes in builder files
area/builder:
  - changed-files:
    - any-glob-to-any-files: 'builder/**'

# Add 'area/cli' label to changes in the CLI
area/cli:
  - changed-files:
    - any-glob-to-any-files: 
      - cmd/**
      - commands/**

# Add 'area/controller' label to changes in the controller
area/controller:
  - changed-files:
    - any-glob-to-any-files: 'controller/**'

# Add 'area/docs' label to markdown files in the docs folder
area/docs:
  - changed-files:
    - any-glob-to-any-files: 'docs/**/*.md'

## Add 'impact/docs' label to markdown files in the docs folder
impact/docs:
  - changed-files:
    - any-glob-to-any-files: 'docs/**/*.md'

# Add 'needs/docs-review' label to markdown files in the docs folder
needs/docs-review:
  - changed-files:
    - any-glob-to-any-files: 'docs/**/*.md'

# Add 'area/dependencies' label to changes in go dependency files
area/dependencies:
  - changed-files:
    - any-glob-to-any-files:
      - go.mod
      - go.sum
      - vendor/**

# Add 'area/driver' label to changes in the driver folder
area/driver:
  - changed-files:
    - any-glob-to-any-files: 'driver/**'

# Add 'area/driver/bkimage' label to changes in the bkimage driver
area/driver/bkimage:
  - changed-files:
    - any-glob-to-any-files: 'driver/bkimage/**'

# Add 'area/driver/docker' label to changes in the docker driver
area/driver/docker:
  - changed-files:
    - any-glob-to-any-files: 'driver/docker/**'

# Add 'area/driver/docker-container' label to changes in the docker-container driver
area/driver/docker-container:
  - changed-files:
    - any-glob-to-any-files: 'driver/docker-container/**'

# Add 'area/driver/kubernetes' label to changes in the kubernetes driver
area/driver/kubernetes:
  - changed-files:
    - any-glob-to-any-files: 'driver/kubernetes/**'

# Add 'area/driver/remote' label to changes in the remote driver
area/driver/remote:
  - changed-files:
    - any-glob-to-any-files: 'driver/remote/**'

# Add 'area/hack' label to changes in the hack folder
area/hack:
  - changed-files:
    - any-glob-to-any-files: 'hack/**'

# Add 'area/tests' label to changes in test files
area/tests:
  - changed-files:
    - any-glob-to-any-files: 'tests/**'